tcp:
  routers:
    k8s-api:
      entryPoints:
        - k8s
      rule: "HostSNI(`*`)"
      service: k8s-api-service
    ingress-http:
      entryPoints:
        - web
      rule: "HostSNI(`*`)"
      service: ingress-http-service
    ingress-https:
      entryPoints:
        - websecure
      rule: "HostSNI(`*`)"
      service: ingress-https-service

  services:
    k8s-api-service:
      loadBalancer:
        servers:
          - address: "controller1:6443"
          - address: "controller2:6443"
          - address: "controller3:6443"
    ingress-http-service:
      loadBalancer:
        servers:
          - address: "worker1:80"
    ingress-https-service:
      loadBalancer:
        servers:
          - address: "worker1:443"
