name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions: {}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: 'false'
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: false
          LINTER_RULES_PATH: .
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          SAVE_SUPER_LINTER_SUMMARY: true
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_ENV: true
          VALIDATE_GO_RELEASER: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: true
          VALIDATE_HTML: true
          VALIDATE_JSON: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_RENOVATE: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
